app:
  name: spring-boot-jpa-example

server:
  port: 8084
  undertow:
    buffer-size: 1024
    direct-buffers: true
    io-threads: 1
    worker-threads: 50

spring:
  application:
    name: spring-boot-jpa-example
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update

